# Generated by Django 4.2.11 on 2024-05-11 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estadoturno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_turno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obra_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra', models.CharField(max_length=100)),
                ('descripcion_obra', models.CharField(max_length=100)),
                ('contacto_obra', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='api.obra_social')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='api.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateField(null=True)),
                ('hora_turno', models.TimeField(null=True)),
                ('estado_turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.estadoturno')),
                ('paciente', models.ForeignKey(default='00:00', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.paciente')),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.profesional')),
            ],
        ),
    ]
