# Generated by Django 4.2 on 2024-06-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Estadoturno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_turno', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado Turno',
                'verbose_name_plural': 'Estado Turnos',
            },
        ),
        migrations.CreateModel(
            name='Obra_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra', models.CharField(max_length=100)),
                ('descripcion_obra', models.CharField(max_length=100)),
                ('contacto_obra', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='api.obra_social')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='api.especialidad')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateField(null=True)),
                ('hora_turno', models.TimeField(null=True)),
                ('estado_turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.estadoturno')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.paciente')),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.profesional')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
